# coding: utf-8

"""
    aiproductdataenhancer/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aiproductdataenhancer.models.aiproductdataenhancer_job_status import AiproductdataenhancerJobStatus

class TestAiproductdataenhancerJobStatus(unittest.TestCase):
    """AiproductdataenhancerJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAiproductdataenhancerJobStatus(self):
        """Test AiproductdataenhancerJobStatus"""
        # inst = AiproductdataenhancerJobStatus()

if __name__ == '__main__':
    unittest.main()
