# coding: utf-8

"""
    aiproductdataenhancer/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aiproductdataenhancer.models.product_information_image_info import ProductInformationImageInfo

class TestProductInformationImageInfo(unittest.TestCase):
    """ProductInformationImageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductInformationImageInfo:
        """Test ProductInformationImageInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductInformationImageInfo`
        """
        model = ProductInformationImageInfo()
        if include_optional:
            return ProductInformationImageInfo(
                url = '',
                metadata = {
                    'key' : ''
                    }
            )
        else:
            return ProductInformationImageInfo(
        )
        """

    def testProductInformationImageInfo(self):
        """Test ProductInformationImageInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
