# coding: utf-8

"""
    aiproductdataenhancer/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aiproductdataenhancer.api.ai_product_data_enhancer_api import AiProductDataEnhancerApi


class TestAiProductDataEnhancerApi(unittest.TestCase):
    """AiProductDataEnhancerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AiProductDataEnhancerApi()

    def tearDown(self) -> None:
        pass

    def test_ai_product_data_enhancer_fill_product_data(self) -> None:
        """Test case for ai_product_data_enhancer_fill_product_data

        """
        pass

    def test_ai_product_data_enhancer_translate_data(self) -> None:
        """Test case for ai_product_data_enhancer_translate_data

        """
        pass


if __name__ == '__main__':
    unittest.main()
