# coding: utf-8

"""
    aiproductdataenhancer/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aiproductdataenhancer.models.generate_product_data_request_product_data_to_generate import GenerateProductDataRequestProductDataToGenerate

class TestGenerateProductDataRequestProductDataToGenerate(unittest.TestCase):
    """GenerateProductDataRequestProductDataToGenerate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateProductDataRequestProductDataToGenerate:
        """Test GenerateProductDataRequestProductDataToGenerate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateProductDataRequestProductDataToGenerate`
        """
        model = GenerateProductDataRequestProductDataToGenerate()
        if include_optional:
            return GenerateProductDataRequestProductDataToGenerate(
                name = '',
                value_set = [
                    ''
                    ],
                metadata = {
                    'key' : ''
                    },
                tone = aiproductdataenhancer.models.aiproductdataenhancer_tone.aiproductdataenhancerTone(
                    tone_type = 'TONE_TYPE_UNKNOWN', 
                    custom_tone = '', )
            )
        else:
            return GenerateProductDataRequestProductDataToGenerate(
        )
        """

    def testGenerateProductDataRequestProductDataToGenerate(self):
        """Test GenerateProductDataRequestProductDataToGenerate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
