# coding: utf-8

"""
    aiproductdataenhancer/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aiproductdataenhancer.models.aiproductdataenhancer_generate_product_data_request_product_information import AiproductdataenhancerGenerateProductDataRequestProductInformation

class TestAiproductdataenhancerGenerateProductDataRequestProductInformation(unittest.TestCase):
    """AiproductdataenhancerGenerateProductDataRequestProductInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AiproductdataenhancerGenerateProductDataRequestProductInformation:
        """Test AiproductdataenhancerGenerateProductDataRequestProductInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AiproductdataenhancerGenerateProductDataRequestProductInformation`
        """
        model = AiproductdataenhancerGenerateProductDataRequestProductInformation()
        if include_optional:
            return AiproductdataenhancerGenerateProductDataRequestProductInformation(
                text_info = aiproductdataenhancer.models.product_information_text_info.ProductInformationTextInfo(
                    name = '', 
                    value = '', 
                    metadata = {
                        'key' : ''
                        }, ),
                image_info = aiproductdataenhancer.models.product_information_image_info.ProductInformationImageInfo(
                    url = '', 
                    metadata = {
                        'key' : ''
                        }, )
            )
        else:
            return AiproductdataenhancerGenerateProductDataRequestProductInformation(
        )
        """

    def testAiproductdataenhancerGenerateProductDataRequestProductInformation(self):
        """Test AiproductdataenhancerGenerateProductDataRequestProductInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
