# coding: utf-8

"""
    aiproductdataenhancer/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aiproductdataenhancer.models.aiproductdataenhancer_tone_type import AiproductdataenhancerToneType

class TestAiproductdataenhancerToneType(unittest.TestCase):
    """AiproductdataenhancerToneType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAiproductdataenhancerToneType(self):
        """Test AiproductdataenhancerToneType"""
        # inst = AiproductdataenhancerToneType()

if __name__ == '__main__':
    unittest.main()
