# coding: utf-8

"""
    aiproductdataenhancer/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AiproductdataenhancerJobStatus(str, Enum):
    """
    AiproductdataenhancerJobStatus
    """

    """
    allowed enum values
    """
    JOB_STATUS_UNKNOWN = 'JOB_STATUS_UNKNOWN'
    JOB_STATUS_PENDING = 'JOB_STATUS_PENDING'
    JOB_STATUS_RUNNING = 'JOB_STATUS_RUNNING'
    JOB_STATUS_COMPLETED = 'JOB_STATUS_COMPLETED'
    JOB_STATUS_FAILED = 'JOB_STATUS_FAILED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AiproductdataenhancerJobStatus from a JSON string"""
        return cls(json.loads(json_str))


