# coding: utf-8

"""
    aiproductdataenhancer/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from aiproductdataenhancer.models.aiproductdataenhancer_data_to_translate import AiproductdataenhancerDataToTranslate
from aiproductdataenhancer.models.aiproductdataenhancer_language_code import AiproductdataenhancerLanguageCode
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AiproductdataenhancerTranslateDataRequest(BaseModel):
    """
    AiproductdataenhancerTranslateDataRequest
    """ # noqa: E501
    tenant_id: Optional[StrictStr] = Field(default=None, alias="tenantId")
    target_language: Optional[AiproductdataenhancerLanguageCode] = Field(default=None, alias="targetLanguage")
    source_language: Optional[AiproductdataenhancerLanguageCode] = Field(default=None, alias="sourceLanguage")
    data_to_translate: Optional[List[AiproductdataenhancerDataToTranslate]] = Field(default=None, alias="dataToTranslate")
    __properties: ClassVar[List[str]] = ["tenantId", "targetLanguage", "sourceLanguage", "dataToTranslate"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AiproductdataenhancerTranslateDataRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data_to_translate (list)
        _items = []
        if self.data_to_translate:
            for _item in self.data_to_translate:
                if _item:
                    _items.append(_item.to_dict())
            _dict['dataToTranslate'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AiproductdataenhancerTranslateDataRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantId": obj.get("tenantId"),
            "targetLanguage": obj.get("targetLanguage"),
            "sourceLanguage": obj.get("sourceLanguage"),
            "dataToTranslate": [AiproductdataenhancerDataToTranslate.from_dict(_item) for _item in obj.get("dataToTranslate")] if obj.get("dataToTranslate") is not None else None
        })
        return _obj


